spring:
  application:
    name: Order-System
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.40.129:3306/ordersystem?useUnicode=true&characterEncoding=utf8

server:
  port: 8080